/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.vendedor;

import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Vendedor;

/**
 * Jframe el cual lista los vendedores incluidos en BD
 * @author camilo
 */
public class ListarVendedor extends javax.swing.JFrame {

    /**
     * Crteeas new form ListarVendedor
     */
    private int rut_vendedor;
    private String nombre;
    private String apellido;
    private int contacto;
    DefaultTableModel tabla;
    
    /** 
     * metodo necesario para habilitar botones en caso de ser seleccionado un elemento de la tabla
     */
    private void habilitarBotones(){
      btn_actualizar.setEnabled(true);
      btn_eliminar.setEnabled(true);
      
    }
    /**
     * metodo para deshabilitar botones al inicio
     */
    private void deshabilitarBotones(){
       btn_actualizar.setEnabled(false);
       btn_eliminar.setEnabled(false);
    }

    public ListarVendedor() {
        initComponents();
        listarVendedor();
        deshabilitarBotones();
    }
    /**
     * metodo necesario para listar y agregar en tabla los vendedors extraidos de la BD
     */
    private void listarVendedor() {
        tabla = new DefaultTableModel();
        Vendedor vendedor = new Vendedor();
        ArrayList<Vendedor> listaVendedor = new ArrayList();
        listaVendedor = vendedor.listarVendedor();
        tabla.addColumn("Rut");
        tabla.addColumn("Nombre");
        tabla.addColumn("Apellido");
        tabla.addColumn("Contacto");
        tabla.addColumn("Fecha de Registro");
        tabla.addColumn("Usuario Registro");
        tabla.setRowCount(listaVendedor.size());
        
        int i= 0;
        for(Vendedor t : listaVendedor){
           tabla.setValueAt(t.getRut_vendedor(), i, 0);
           tabla.setValueAt(t.getNombre(), i, 1);
           tabla.setValueAt(t.getApellido(), i, 2);
           tabla.setValueAt(t.getContacto(), i, 3);
           i++;
        }
        this.tbl_vendedor.setModel(tabla);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_vendedor = new javax.swing.JTable();
        btn_actualizar = new javax.swing.JButton();
        btn_eliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        tbl_vendedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Rut", "Nombre"
            }
        ));
        tbl_vendedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_vendedorMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_vendedor);

        btn_actualizar.setText("Actualizar");
        btn_actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_actualizarActionPerformed(evt);
            }
        });

        btn_eliminar.setText("Eliminar");
        btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 505, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(btn_actualizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_eliminar)
                .addGap(120, 120, 120))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_actualizar)
                    .addComponent(btn_eliminar))
                .addGap(47, 47, 47))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarActionPerformed
        
        int respuesta = JOptionPane.showConfirmDialog(rootPane, "¿Desea eliminar al vendedor?");
        if(respuesta==0){
          Vendedor vendedor = new Vendedor();
          vendedor.setRut_vendedor(rut_vendedor);
          vendedor.eliminarDatos();
          listarVendedor();
        }


    }//GEN-LAST:event_btn_eliminarActionPerformed

    private void btn_actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_actualizarActionPerformed
        Vendedor vendedor = new Vendedor();
        vendedor.setRut_vendedor(rut_vendedor);
        vendedor.setNombre(nombre);
        vendedor.setApellido(apellido);
        vendedor.setContacto(contacto);
        
        
        
        ActualizarVendedor actualizarVendedor = new ActualizarVendedor();
        actualizarVendedor.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
        actualizarVendedor.setVisible(true);
    }//GEN-LAST:event_btn_actualizarActionPerformed

    private void tbl_vendedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_vendedorMouseClicked
        habilitarBotones();
        rut_vendedor = Integer.parseInt(tabla.getValueAt(tbl_vendedor.getSelectedRow(), 0).toString());
        nombre = tabla.getValueAt(tbl_vendedor.getSelectedRow(),0).toString();
        apellido = tabla.getValueAt(tbl_vendedor.getSelectedRow(),0).toString();
        contacto = Integer.parseInt(tabla.getValueAt(tbl_vendedor.getSelectedRow(), 0).toString());
    }//GEN-LAST:event_tbl_vendedorMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListarVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListarVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListarVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListarVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListarVendedor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_actualizar;
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_vendedor;
    // End of variables declaration//GEN-END:variables
}
